# Generated by Django 2.2.4 on 2021-06-15 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('la_pared', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='mensajes',
            options={'ordering': ['-created_at']},
        ),
    ]
