# Generated by Django 2.2.4 on 2021-06-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0002_auto_20210612_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cumpleaños',
            field=models.DateField(default='1990-03-25'),
            preserve_default=False,
        ),
    ]
